[general]
api_key = "ed_dzv4ddrw1oq9ca7sn75xjdyqejxq496ku8l6sk9u4i3pf5f86x8axv8bwq9r4unh"
device_id = "2d9b5760-afe9-11ee-a8fb-b92f34d9b31d"

[google_service_account]
type = "service_account"
project_id = "edenic-468023"
private_key_id = "44d9c0c93e339ef297222fb50787e1c655852891"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC2jSIMRXCKQNlb
9CFfoVpLmfv5GDxId5ZBgbnY5oN9j4IOgufkGtl5s/LrUGR41xO8+XwMxpzHI4k7
nZfIKF3n5G2tirw1uyytEmhbXmIFbt3lODrYRGxU0yQQavSYo9rYwLiNM4ONIW1u
87ZQnWxtPBcE1X/7UcQopsFJ6AY8rVk9dOWo2o4NCmeeL0TtuifbVpboerS1b6d/
JEHKvjs+YWyIwICGvecnmEgb+M3QybSmReZ6fgJrjNaPauC65aROfALT/sSjmAqB
nK24FRl9FLbgCvfybKiF/fRQqkusWFIFdlyrfOhM1Z6eazzzY1aqn2b1WZBpf3Hc
1JLAKctJAgMBAAECggEABj1GJ5rcH/UAP7gC2iVK2L5MfYmEe/NzRnJBvrPIQobX
ipmlKiedNA0SugsGITw0X64ptBPwwMXToIyJZxGy/fa2N6s27GGlMN8FcXG8AAJT
Bihv89//rOKsI6I6f0/L0vmEvCOc/jEziyWp8XV/Z1P01+JYo5VDd6Jel4XBw/Vz
LJq0vnw/pbRqVok0CKTj4MfaP5imRPhhjYbk6e/AviPJSwbnBD2eIAKD3M3n3CeP
JnvT9jLzJFtvVfbnO04CRNIWaZK62hWHB7iFIqvQboFiPUUNReZfHs7XfybLlas/
zbfEJlXYvIdEdsAhIY4gAe/viDw1//AFYxpSUcIv5QKBgQD5YjcHeR7YPV4BmeQ9
QRmaf68/GaNwRx0bvuKpPVlntIh2gm7RlkPtA2DL7Z+qmFq2n6i/Pn90zSVig2E6
lY9kTFYMEQmmrfFAeEFFIu/tzssp9FqyquwH6ScJ2AXaHuGKg1NUs8jBrWhs2EzR
NMHYO4Jjc8RhdmtR8cqT6gdl3QKBgQC7ZQAay0u1pz27Cj5aODjEtfexJVbzMxu/
GNbWdEv+Qe3CyLMoURhnNMjfmFkJg+OPLrPlAXb6NLEMezp9FKK8me4uaM0PRTi/
+bGlkNhCezvvPUf0MI0FbShJVbK/VmeP01SFQHoKKcJISmNI1EFF3vRKPi2qQ9+Z
3GtGeS1SXQKBgARiNZVsC57BdWWRzvFEs66DkBEL4lOW7GwQbuuKqIeqJLvwjwIg
IhGIfasYAjZ9dxq+s7io4JStBns01ACzoFGjBeAwbHsBk7wOYRdWBeGoQOn74ZxC
ZOO+tXD22yN6Z3yH0m8qudytr6g6JR+ITd//K8uTvV/5NOm71lPDSV4BAoGBAKUT
BLOVr/y19SAFlwWcjw1him7nCKA1vlRpSh8h1SuF4i764y85uLh5fBXTO2OxZczk
hB3QW4Fu1yO6jbxPaEehhXomYbT48lPSXhYN8SMnMZW+stq9xgwoqxtmvY3lTFca
/1JeiOLZBEbwGGO4bkNhcmrQOSPKpHcB/xHWfwEVAoGANmMF4pCVusXk+6RnFTP8
qKQBdBfD+zH3lThhutHqDFJvLreI2rlbtbNqXlE/Y0Rzp5jC7w5HCAK4cyLd/tv4
fSHyPda5pyNjDzT6Iw4McDuFxDRahcK5k2H+YHHhEn+Z4Sj8vjspSguPasd2tN9O
KIU7W4FoEMNRlR1xU917qwI=
-----END PRIVATE KEY-----"""
client_email = "edenicstelemetry@edenic-468023.iam.gserviceaccount.com"
client_id = "116508953215839271481"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/edenicstelemetry%40edenic-468023.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
